import { dom, library, config } from "~/@fortawesome/fontawesome-svg-core";
import {
    faEraser,
    faArrowLeftLong,
    faPlus,
    faMinus,
    faTrash,
    faEye,
    faFolderOpen,
    faCrop,
    faQuestionCircle,
    faCheck,
    faUndoAlt,
    faRedoAlt,
    faSyncAlt,
    faSearchPlus,
    faSearchMinus,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowDown,
    faArrowsAltH,
    faArrowsAltV,
    faWandMagic,
    faPencil,
    faTimes,
    faBackspace,
    faSearch,
    faArrowRightFromBracket,
    faArrowAltCircleDown,
    faArrowAltCircleUp,
    faQuestion,
    faXmark,
    faCopy,
    faFile,
    faLink,
    faPrint,
    faImage,
    faDownload,
} from "~/@fortawesome/free-solid-svg-icons";

config.autoReplaceSvg = false;
library.add(faEraser);
library.add(faArrowLeftLong);
library.add(faPlus);
library.add(faMinus);
library.add(faTrash);
library.add(faEye);
library.add(faFolderOpen);
library.add(faCrop);
library.add(faQuestionCircle);
library.add(faCheck);
library.add(faUndoAlt);
library.add(faRedoAlt);
library.add(faSyncAlt);
library.add(faSearchPlus);
library.add(faSearchMinus);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faArrowUp);
library.add(faArrowDown);
library.add(faArrowsAltH);
library.add(faArrowsAltV);
library.add(faWandMagic);
library.add(faPencil);
library.add(faTimes);
library.add(faBackspace);
library.add(faSearch);
library.add(faArrowRightFromBracket);
library.add(faArrowAltCircleDown);
library.add(faArrowAltCircleUp);
library.add(faQuestion);
library.add(faXmark);
library.add(faCopy);
library.add(faFile);
library.add(faLink);
library.add(faPrint);
library.add(faImage);
library.add(faDownload);

dom.watch();
